- name: Install locales "{{ locale }}"
  locale_gen: name="{{ locale }}" state=present
  tags:
    - core
    - locale

- name: Configure locale "{{ locale }}"
  command: localectl set-locale LANG=""{{ locale }}""
  tags:
    - core
    - locale

- name: Configure keymap "{{ keymap }}"
  command: localectl set-keymap "{{ keymap }}"
  tags:
    - core
    - locale
    - keymap
