---
- name: Install core utils packages
  pacman: name={{ core_utils }} state=present
  tags:
    - packages
    - core_utils

- name: Clone yay repo
  git: repo=https://aur.archlinux.org/yay.git dest=/tmp/yay/ accept_hostkey=yes update=yes
  become_user: "{{ user.name }}"

- name: Create yay package
  shell: cd /tmp/yay && makepkg -si --noconfirm
  become_user: "{{ user.name }}"

- name: Install tmux splitted pages script
  copy: src=tmux_splitted_pager.sh dest=/home/{{ user.name }}/bin/tmux_splitted_pager.sh
  tags:
    - packages
    - core_utils

- name: Install core debug utils packages
  pacman: name={{ core_debugutils }} state=present
  tags:
    - packages
    - core_debugutils

- name: Install core net utils packages
  pacman: name={{ core_netutils }} state=present
  tags:
    - packages
    - core_netutils

- name: Install core goodies packages
  pacman: name={{ core_goodies }} state=present
  tags:
    - packages
    - core_goodies

- name: Install core aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ core_aur}}"
  when: core_aur is defined
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - packages
    - core_aur
    - aur

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks
        state=directory
  tags:
    - packages

- name: Push pacman mirror list update hook
  copy: src=mirrorupgrade.hook dest=/etc/pacman.d/hooks/mirrorupgrade.hook
  tags:
    - packages
