---
- name: Enable wicd unit
  systemd: daemon_reload=yes name=wicd enabled=yes
  become: yes
  tags:
    - core
    - systemd

- name: Enable systemd-timesyncd unit
  systemd: daemon_reload=yes name=systemd-timesyncd enabled=yes
  become: yes
  tags:
    - core
    - systemd
    - timezone
