arch:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/usr/bin/python3"
    vagrant:
      ansible_host: 192.168.56.2
      ansible_user: vagrant
      ansible_python_interpreter: /usr/bin/python2
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
