---
- name: Install plasma tools
  dnf: 
    name: "{{ plasma_tools }}"
    state: present
  when: desktop == "plasma"

- name: Add flathub repo
  flatpak_remote: 
    name:  flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
  become: yes
  become_user: "{{ user.name }}"

- name: Install touche
  flatpak:
    name: com.github.joseexposito.touche
    state: present
    method: user
  when: desktop == "plasma"
  become: yes
  become_user: "{{ user.name }}"


- name: Install gnome tools
  dnf: 
    name: "{{ gnome_tools }}"
    state: present
  when: desktop == "gnome"

- name: Install Gnome Flatpak tools
  flatpak:
    name: " {{ gnome_flatpaks }}"
    state: present
