---
- name: Install GNOME packages
  pacman: 
    name: "{{ gnome }}"
    state: present
  notify: enable gdm
  when: installde == "True"

- name: Install GNOME packages
  pacman: 
    name: "{{ pkg_gnome }}"
    state: present

- name: Install Gnome AUR packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ aur_gnome }}"
  become: yes
  become_user: "{{ user.name }}"

- name: Install Gnome flatpak tools
  flatpak:
    name: "{{ fpk_gnome }}"
    state: present
