---
- name: Install GNOME packages
  pacman: 
    name: {{ gnome }}
    state: present

- name: Install GNOME Tools packages
  pacman: 
    name: {{ gnome_tools }}
    state: present

- name: Install Gnome AUR packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ gnome_aur }}"
  when: core_aur is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Enable GDM service
  ansible.builtin.systemd:
    name: gdm.service
    state: started
    enabled: yes