---
- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    
- name: Include arch config
  include_tasks: "{{ item }}"
  loop:
    - packages.yml
    - "{{ desktop }}.yml"

- name: Install xorg keyboard settings
  copy: 
    src: 00-keyboard.conf 
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf 
    owner: root 
    group: root 
    mode: 0644

- name: Install xorg touchpad settings
  copy: 
    src: 30-touchpad.conf 
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf 
    owner: root 
    group: root 
    mode: 0644
  when: laptop == true
