---
- name: Install KDE Plasma packages
  pacman: 
    name: "{{ plasma }}"
    state: present
  notify: enable sddm
  when: installde == "True"

- name: Install KDE Plasma Tools packages
  pacman: 
    name: "{{ pkg_plasma }}"
    state: present

- name: Install KDE Plasma AUR packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ aur_plasma }}"
  become: yes
  become_user: "{{ user.name }}"