---
- name: Add flathub repo
  flatpak_remote: 
    name:  flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
  become: yes
  become_user: "{{ user.name }}"

- name: Install gnome tools
  apt: 
    name: "{{ gnome_tools }}"
    state: latest

- name: Install Gnome flatpak tools
  flatpak:
    name: "{{ gnome_flatpaks }}"
    state: present
