---
- name: Install WM Packages
  pacman: 
    name: "{{ wm }}"
    state: present
  when: installde == true

- name: Install BSPWM AUR packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ aur_wm }}"
  become: true
  become_user: "{{ user.name }}"

- name: Install Oh-My-Zsh
  shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" "" --unattended
  become: true
  become_user: "{{ user.name }}"

- name: Clone Dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: "/home/{{ user.name }}/.dotfiles"
    bare: yes
  become: true
  become_user: "{{ user.name }}"

- name: Install Dotfiles
  shell: git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout -f
  become: true
  become_user: "{{ user.name }}"
