---
- name: Install npm packages
  shell: "npm install -g pnpm && npm install -g yarn"

- name: Download Lunarvim
  get_url: 
    url: https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
    dest: /home/{{ user.name }}/install.sh
    mode: 0766
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install Lunarvim
  shell: /home/{{ user.name }}/install.sh -y
  become: true
  become_user: "{{ user.name }}"