---
- name: Install Netutils packages
  pacman: 
    name: "{{ pkg_netutils }}"
    state: present

- name: Install Others packages
  pacman: 
    name: "{{ pkg_others }}"
    state: present

- name: Install Tools packages
  pacman: 
    name: "{{ pkg_tools }}"
    state: present
