---
- name: Install gui core packages
  pacman: name={{ gui_core }} state=present
  tags:
    - packages
    - gui
    - gui_core

- name: Install xorg keyboard settings
  copy: src=10-keyboard.conf dest=/etc/X11/xorg.conf.d/10-keyboard.conf owner=root group=root mode=0644
  tags:
    - gui
    - gui_core

- name: Install gui video drivers
  pacman: name={{ gui_video_drivers }} state=present
  tags:
    - packages
    - gui
    - gui_video_drivers

- name: Install gui de/wm packages
  pacman: name={{ gui_ui }} state=present
  tags:
    - packages
    - gui
    - gui_ui

- name: Install naughty send script for notification
  copy: src=naughty-send.sh dest=/home/{{ user.name }}/bin/naughty-send.sh
  tags:
    - packages
    - gui
    - gui_utility

- name: Install gui utility packages
  pacman: name={{ gui_utility }} state=present
  tags:
    - packages
    - gui
    - gui_utility

- name: Install gui themes packages
  pacman: name={{ gui_themes }} state=present
  tags:
    - packages
    - gui
    - gui_themes

- name: Install gui aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ gui_aur}}"
  become: yes
  become_user: "{{ user.name }}"
  when: gui_aur is defined
  tags:
    - packages
    - gui
    - gui_aur
    - aur
