---
- name: Install gui core packages
  pacman: name={{ item }} state=present
  with_items: "{{ gui_core }}"
  tags:
    - packages
    - gui
    - gui_core

- name: Install gui video drivers
  pacman: name={{ item }} state=present
  with_items: "{{ gui_video_drivers }}"
  tags:
    - packages
    - gui
    - gui_video_drivers

- name: Install gui de/wm packages
  pacman: name={{ item }} state=present
  with_items: "{{ gui_ui }}"
  tags:
    - packages
    - gui
    - gui_ui

- name: Install naughty send script for notification
  copy: src=naughty-send.sh dest=/home/{{ user.name }}/bin/naughty-send.sh
  tags:
    - packages
    - gui
    - gui_utility

- name: Install gui utility packages
  pacman: name={{ item }} state=present
  with_items: "{{ gui_utility }}"
  tags:
    - packages
    - gui
    - gui_utility

- name: Install slock wrapper
  copy: src=slock dest=/usr/bin/slock
  tags:
    - packages
    - gui
    - gui_utility

- name: Install gui themes packages
  pacman: name={{ item }} state=present
  with_items: "{{ gui_themes }}"
  tags:
    - packages
    - gui
    - gui_themes

- name: Install gui aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ gui_aur}}"
  become: yes
  become_user: "{{ user.name }}"
  when: gui_aur is defined
  tags:
    - packages
    - gui
    - gui_aur
    - aur
