---
- name: dnf optimizations
  shell: "{{ item }}"
  loop:
    - "echo 'fastestmirror=1' | sudo tee -a /etc/dnf/dnf.conf"
    - "echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf"
    - "echo 'deltarpm=true' | sudo tee -a /etc/dnf/dnf.conf"

- name: Adjust RPM Fusion free repo name
  shell: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm

- name: Adjust RPM Fusion nonfree repo name
  shell: dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm

- name: Adjust Notion app enhancer
  copy: 
   src: notion-repackaged.repo
   dest: /etc/yum.repos.d/notion-repackaged.repo
   mode: 0644
   owner: root
   group: root

- name: Install core utils packages
  dnf: 
    name: '{{ core_packages }}' 
    state: present
