---
- name: Set the hostname
  hostname: 
    name: '{{ hostname }}'
  when: hostname is defined
    
- name: Create user and assign to groups
  shell: useradd --badnames {{ user.name }} -m -s {{ user.shell }} -u {{ user.uid }} -G wheel
  ignore_errors: yes

- name: Include locale tasks 
  include_tasks: locale.yml
  when: os != "fedora"

- name: Include other core tasks
  include_tasks: "{{ item }}"
  loop:
    - timezone.yml
    - "{{ os }}-packages.yml"
    - systemd.yml

- name: Copy sudo configuration
  copy: 
   src: sudoers
   dest: /etc/sudoers
   mode: 0440
   validate: 'visudo -cf %s'
   