---
- name: Install core utils packages
  pacman: 
    name: '{{ core_packages }}' 
    state: present

- name: Copy sudo configuration
  copy: 
   src: sudoers
   dest: /etc/sudoers
   mode: 0440
   validate: 'visudo -cf %s'
   
- name: Clone yay repo
  git: 
    repo: https://aur.archlinux.org/yay.git 
    dest: /tmp/yay/ 
    accept_hostkey: yes 
    update: yes
  become_user: "{{ user.name }}"

- name: Create yay package
  shell: cd /tmp/yay && makepkg -si --noconfirm
  become_user: "{{ user.name }}"

- name: Install core aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ core_aur }}"
  when: core_aur is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Create pacman hook directory
  file: 
    path: /etc/pacman.d/hooks
    state: directory

- name: Push pacman mirror list update hook
  copy: 
    src: mirrorupgrade.hook
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook