---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Sort mirror by reflector
  shell: reflector --latest 50 --age 24 --sort rate --save /etc/pacman.d/mirrorlist

- name: Use all cores when compressing packages
  lineinfile:
    dest: /etc/makepkg.conf 
    regexp: "^COMPRESSXZ" 
    line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Copy nobeep configuration
  copy:
    src: nobeep.conf 
    dest: /etc/modprobe.d/nobeep.conf 
    mode: 0440

- name: Install core utils packages
  pacman:
    name: '{{ pkg_core }}' 
    state: present

- name: Clone yay repo
  git:
    repo: https://aur.archlinux.org/yay.git 
    dest: /tmp/yay/ 
    accept_hostkey: yes 
    update: yes
  become_user: "{{ user.name }}"

- name: Create yay package
  shell: cd /tmp/yay && makepkg -si --noconfirm
  become_user: "{{ user.name }}"

- name: Install core aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ aur_core }}"
  when: aur_core is defined
  become: true
  become_user: "{{ user.name }}"

- name: Create pacman hook directory
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Push pacman mirror list update hook
  copy:
    src: mirrorupgrade.hook
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
