---
- name: apt optimizations
  shell: "sudo sed -i 's|http://us.|http://br.|' /etc/apt/sources.list.d/system.sources"

- name: Adjust Notion app enhancer
  shell: echo "deb [trusted=yes] https://apt.fury.io/notion-repackaged/ /" | sudo tee /etc/apt/sources.list.d/notion-repackaged.list

- name: Install core utils packages
  apt: 
    name: '{{ core_packages }}' 
    state: latest
    update_cache: yes
