---
- name: Install xorg keyboard settings
  copy: 
    src: 10-keyboard.conf 
    dest: /etc/X11/xorg.conf.d/10-keyboard.conf 
    owner: root 
    group: root 
    mode: 0644

- name: Install xorg touchpad settings
  copy: 
    src: 30-touchpad.conf 
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf 
    owner: root 
    group: root 
    mode: 0644