---
- name: Install audio core packages
  pacman: name={{ audio_core }} state=present
  tags:
    - packages
    - cli
    - audio_core

- name: Install audio players packages
  pacman: name={{ audio_players }} state=present
  tags:
    - packages
    - cli
    - audio_players

- name: Install audio aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ audio_aur }}"
  when: core_aur is defined
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - packages
    - aur
    - cli
