---
- name: Install chaotic-aur keys
  community.general.pacman_key:
    id: 3056513887B78AEB
    keyserver: keyserver.ubuntu.com

- name: Install chaotic-aur keyring
  shell: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'

- name: Install chaotic-aur mirrorlist
  shell: pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

- name: Add chaotic-aur to pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    append_newline: true
    prepend_newline: true
    block: |
      [chaotic-aur]
      Include = /etc/pacman.d/chaotic-mirrorlist