---
- name: Import pacman config tasks
  include_task: pacman.yml

- name: Import AUR config tasks
  include_task: aur.yml

- name: Import Nix package manager task
  include_task: nix.yml

- name: Import chaotic-aur install task
  include_task: chaotic.yml
