- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Update Arch keyring
  pacman:
    name: archlinux-keyring
    state: latest

- name: Import a key via keyserver
  community.general.pacman_key:
    id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A
    keyserver: keyserver.ubuntu.com