---
- name: Download Nix install script
  get_url: 
    url: https://nixos.org/nix/install
    dest: /tmp/nix-install
    mode: 0744

- name: Run the Nix install script
  script:
    cmd: /tmp/nix-install --daemon --yes