- name: Load packages variable
  include_vars:
    file: wm.yml

- name: Install WM packages
  pacman:
    name: "{{ wm_pkg }}"
    state: present

- name: Install aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ wm_aur }}"
  become: true
  become_user: "{{ user.name }}"

- name: Clone Dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: "/home/{{ user.name }}/.dotfiles"
    bare: true
  become: true
  become_user: "{{ user.name }}"

- name: Install Dotfiles
  shell: git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout -f
  become: true
  become_user: "{{ user.name }}"
