---
- name: Remove vim to install gvim
  pacman: name=vim state=absent
  tags:
    - packages
    - tools
    - gui

- name: Install tools packages
  pacman: name={{ item }} state=present
  with_items: "{{ tools }}"
  tags:
    - packages
    - tools
    - gui
