---
- name: Remove vim to install gvim
  pacman: name=vim state=absent
  tags:
    - packages
    - tools
    - gui

- name: Install tools packages
  pacman: name={{ tools }} state=present
  tags:
    - packages
    - tools
    - gui

- name: Install tools aur packages
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ tools_aur }}"
  when: core_aur is defined
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - packages
    - tools
    - aur
    - gui

