---

- name: enable sddm
  ansible.builtin.systemd:
    name: sddm.service
    state: started
    enabled: yes

- name: enable gdm
  ansible.builtin.systemd:
    name: gdm.service
    state: started
    enabled: yes