- name: Load packages variable
  include_vars:
    file: crmall_packages.yml

- name: Install packages needed for work
  pacman:
    name: "{{ crmall_packages }}"
    state: present

- name: Install aur packages needed for work
  shell: yay --noconfirm -S {{ item }}
  with_items: "{{ crmall_aur }}"
  become: true
  become_user: "{{ user.name }}"

