wm_pkg:
    - hyprland
    - waybar
    - dunst
    - rofi
    - swaybg
    - grim
    - slurp
    - pamixer
    - nautilus
    - ttf-jetbrains-mono-nerd
    - brightnessctl
    - playerctl
    - lxappearance-gtk3
    - python-pywal
    - imagemagick
    - polkit-gnome
    - acpi
    - xfce4-power-manager
    - xorg-xbacklight

wm_aur:
    - wlogout
#    - swww
    - swaybg
    - zscroll
    - nerd-fonts-jetbrains-mono
    - nerd-fonts-fira-code
    - montserrat-ttf
    - rxfetch
    - pfetch
